### ISSUE TITLE
GPTOpen not an editor command

### ISSUE THREAD

**Issue by KoushikSahu** [archibate/nvim-gpt#4]
I tried installing this plugin and even after setting up everything as per the README  I am getting an error while trying the plugin commands that they do not exist.

The only step I did differently was to install using Lazy rather than Packer.

**Comment by archibate** [comment]
Have you tried :UpdateRemotePlugin as described in README.md?











无法顺畅的大口呼吸，是活着的最好证明

---Original---
From: "Koushik ***@***.***&gt;
Date: Sun, Jul 16, 2023 18:43 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [archibate/nvim-gpt] GPTOpen not an editor command (Issue #4)




 
I tried installing this plugin and even after setting up everything as per the README  I am getting an error while trying the plugin commands that they do not exist.
 
The only step I did differently was to install using Lazy rather than Packer.

**Comment by KoushikSahu** [comment]
Running `:UpdateRemotePlugin` fixed the issue. Closing this issue.
